### ISSUE TITLE
unable to install 2fa module

### ISSUE THREAD

**Issue by senolsun** [ventor-tech/merp#69]
two factor authentication module cannot be installed at all. error is:

Hata:
Odoo Server Error

Traceback (most recent call last):
  File "/odoo/odoo/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/odoo/odoo/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/odoo/odoo/odoo/tools/convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/odoo/odoo/models.py", line 4067, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo/addons/website/models/ir_ui_view.py", line 148, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/odoo/odoo/odoo/models.py", line 3981, in _load_records_create
    return self.create(values)
  File "<decorator-gen-31>", line 2, in create
  File "/odoo/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 473, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/odoo/models.py", line 3762, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/odoo/odoo/fields.py", line 1109, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/odoo/odoo/addons/website/models/ir_ui_view.py", line 51, in write
    return super(View, self).write(vals)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 490, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo/odoo/models.py", line 3551, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/odoo/odoo/odoo/models.py", line 1167, in _validate_fields
    check(self)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 385, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/odoo/odoo/addons/ns_web_debranding/models/ir_ui_view.py", line 16, in read_combined
    res = super(View, self).read_combined(fields=fields)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 716, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 662, in apply_view_inheritance
    specs_tree = etree.fromstring(specs.encode('utf-8'))
AttributeError: 'bool' object has no attribute 'encode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/odoo/odoo/odoo/http.py", line 619, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/odoo/odoo/http.py", line 309, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo/odoo/odoo/http.py", line 664, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/odoo/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/odoo/odoo/addons/web/controllers/main.py", line 1324, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/odoo/odoo/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/odoo/odoo/api.py", line 395, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo/odoo/odoo/api.py", line 382, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/odoo/addons/stock/models/res_config_settings.py", line 89, in execute
    res = super(ResConfigSettings, self).execute()
  File "/odoo/odoo/odoo/addons/base/models/res_config.py", line 630, in execute
    self._install_modules(to_install)
  File "/odoo/odoo/odoo/addons/base/models/res_config.py", line 34, in _install_modules
    result = to_install_modules.button_immediate_install()
  File "<decorator-gen-58>", line 2, in button_immediate_install
  File "/odoo/odoo/odoo/addons/base/models/ir_module.py", line 72, in check_and_log
    return method(self, *args, **kwargs)
  File "/odoo/odoo/odoo/addons/base/models/ir_module.py", line 463, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/odoo/odoo/odoo/addons/base/models/ir_module.py", line 573, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/odoo/odoo/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/odoo/odoo/odoo/modules/loading.py", line 420, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/odoo/odoo/odoo/modules/loading.py", line 312, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/odoo/odoo/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/odoo/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/odoo/odoo/odoo/tools/convert.py", line 737, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/odoo/odoo/odoo/tools/convert.py", line 804, in convert_xml_import
    obj.parse(doc.getroot())
  File "/odoo/odoo/odoo/tools/convert.py", line 722, in parse
    exc_info[2]
  File "/odoo/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/odoo/odoo/odoo/tools/convert.py", line 713, in parse
    self._tag_root(de)
  File "/odoo/odoo/odoo/tools/convert.py", line 675, in _tag_root
    f(rec)
  File "/odoo/odoo/odoo/tools/convert.py", line 578, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/odoo/odoo/odoo/models.py", line 4067, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/odoo/odoo/addons/website/models/ir_ui_view.py", line 148, in _load_records_create
    records = super(View, self)._load_records_create(values)
  File "/odoo/odoo/odoo/models.py", line 3981, in _load_records_create
    return self.create(values)
  File "<decorator-gen-31>", line 2, in create
  File "/odoo/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 473, in create
    return super(View, self).create(vals_list)
  File "<decorator-gen-3>", line 2, in create
  File "/odoo/odoo/odoo/api.py", line 344, in _model_create_multi
    return create(self, arg)
  File "/odoo/odoo/odoo/models.py", line 3762, in create
    fields[0].determine_inverse(batch_recs)
  File "/odoo/odoo/odoo/fields.py", line 1109, in determine_inverse
    getattr(records, self.inverse)()
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 299, in _inverse_arch
    view.write(data)
  File "/odoo/odoo/addons/website/models/ir_ui_view.py", line 51, in write
    return super(View, self).write(vals)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 490, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/odoo/odoo/odoo/models.py", line 3551, in write
    real_recs._validate_fields(set(vals) - set(inverse_fields))
  File "/odoo/odoo/odoo/models.py", line 1167, in _validate_fields
    check(self)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 385, in _check_xml
    view_def = view.read_combined(['arch'])
  File "/odoo/odoo/addons/ns_web_debranding/models/ir_ui_view.py", line 16, in read_combined
    res = super(View, self).read_combined(fields=fields)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 716, in read_combined
    arch = self.apply_view_inheritance(arch_tree, root.id, self.model)
  File "/odoo/odoo/odoo/addons/base/models/ir_ui_view.py", line 662, in apply_view_inheritance
    specs_tree = etree.fromstring(specs.encode('utf-8'))
odoo.tools.convert.ParseError: "'bool' object has no attribute 'encode'" while parsing /odoo/odoo/addons/two_factor_otp_auth/views/res_users_view.xml:2, near
<odoo>

    <record id="res_users_form_inherit_2fa" model="ir.ui.view">
        <field name="name">res.users.form.inherit.2fa</field>
        <field name="model">res.users</field>
        <field name="inherit_id" ref="base.view_users_form"/>
        <field name="arch" type="xml">
            <field name="signature" position="before">
                <field name="enable_2fa"/>
                <field name="qr_image_2fa" widget="image" attrs="{                             'invisible': [                             '|',                                 ('enable_2fa', '=', False),                                 ('qr_image_2fa', '=', False),                             ],                         }" readonly="1" groups="two_factor_otp_auth.mass_change_2fa_for_users"/>
            </field>
        </field>
    </record>

    <record id="res_users_tree_inherit_2fa" model="ir.ui.view">
        <field name="name">res.users.tree.inherit.2fa</field>
        <field name="model">res.users</field>
        <field name="inherit_id" ref="base.view_users_tree"/>
        <field name="arch" type="xml">
            <field name="login_date" position="after">
                <field name="enable_2fa"/>
            </field>
        </field>
    </record>

</odoo>

**Comment by okuryan** [comment]
@senolsun , can you tell if you was able to solve your issue and what version of Odoo you are using?
Also on what platform you are installing? (Windows/ Ubuntu..)?

**Comment by okuryan** [comment]
Task is closed due to inactivity
