### ISSUE TITLE
2fa module is not compatible with Odoo official mobile app

### ISSUE THREAD

**Issue by okuryan** [ventor-tech/merp#96]
**Problem Description**

When you are trying to login with Odoo official mobile app. The following error was displayed on Odoo Mobile app interface.
![image](https://user-images.githubusercontent.com/2680904/85918955-dc973880-b86f-11ea-8526-c6c3b7f979c9.png)

In Odoo logs error will be the following:
```
020-06-27 09:13:46,796 15768 ERROR demo13e odoo.http: Exception during JSON request handling. 
Traceback (most recent call last):
  File "/home/ventortech/13.0/odoo/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/ventortech/13.0/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/home/ventortech/13.0/odoo/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/home/ventortech/13.0/odoo/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/home/ventortech/13.0/odoo/odoo/http.py", line 351, in _call_function
    return self.endpoint(*args, **kwargs)
  File "/home/ventortech/13.0/odoo/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/home/ventortech/13.0/odoo/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/ventortech/13.0/odoo/addons/web/controllers/main.py", line 1187, in authenticate
    request.session.authenticate(db, login, password)
  File "/home/ventortech/13.0/odoo/odoo/http.py", line 1006, in authenticate
    uid = odoo.registry(db)['res.users'].authenticate(db, login, password, env)
  File "/home/ventortech/13.0/odoo/odoo/addons/base/models/res_users.py", line 642, in authenticate
    uid = cls._login(db, login, password)
  File "/home/ventortech/13.0/odoo/odoo/addons/base/models/res_users.py", line 621, in _login
    user._check_credentials(password)
  File "/home/ventortech/13.0/all_addons/two_factor_otp_auth/models/res_users.py", line 108, in _check_credentials
    raise MissingOtpError()
odoo.addons.two_factor_otp_auth.exceptions.access_errors.MissingOtpError
```

**Root Cause Analysis**

Reason of this is that Odoo Mobile App is using "/web/session/authenticate" Controller in order to login. And this Controller doesn't assume that there will be redirects after login to the second page. It assumes that there will be redirect

This method is called. It is JSON format and doesn't assume any redirects or rendering new templates https://github.com/odoo/odoo/blob/13.0/addons/web/controllers/main.py#L1186

**Comment by dynapps-ch-jean** [comment]
I just made a fix for myself, which is just to check where the login request comes from when we raise the MissingOtpError(); :+1: 
if "web/login" in request.httprequest.url:
                    raise MissingOtpError()

It works, the OTP is requested when the login comes from the backend and the OTP is not used when a request comes from the app or the API. Of course, better security would be to request the OTP even from the app, so if you have any idea do not hesitate.

**Comment by okuryan** [comment]
@dootix-jean , thank you! Yes, after several hours of investigation internally we also came to the same conclusion. Because mobile app using another methods and formats. So this is limitation we cannot overcome for now except just skipping it..

We will analyze your suggested solution and see if we come up with some other option or your option is the best one. THank you!

**Comment by edoubleoo** [comment]
Hi everyone, 

Wanted to check if this error has been corrected in your latest release of this app? or can you share the correction required to solve this issue?

Thanks.

**Comment by lalabuy948** [comment]
Greetings, is there any news on this issue?

**Comment by finishingtech** [comment]
Hello - Any news on this issue?

**Comment by okuryan** [comment]
@finishingtech you need to use the fix as described on 27 of Jun 2020. The problem is in the bad architecture design of the Odoo mobile app and the way of login. In latest version of Odoo 2FA is built in Odoo itself, so this module no longer needed

**Comment by edoubleoo** [comment]
@okuryan & @dootix-jean

I followed your suggestions and added @dootix-jean suggested solution to the main.py within two_factor_otp_auth module, as below:

`class Login2fa(Home):

    @http.route()
    def web_login(self, redirect=None, **kw):
        """
        Overload core method to start Second Factor validation step
        """
        try:
            response = super(Login2fa, self).web_login(redirect, **kw)
        except MissingOtpError:
            if "web/login" in request.httprequest.url:
               raise MissingOtpError()
            # user will get into this block if login process is not fully successful
            # For example, when first login was successful, but 2FA token is missing
            # So we can start second authentication step (OTP)
            response = self._redirect_to_2fa()
        except InvalidOtpError:
            message = _("Your security code is wrong")
            response = self._redirect_to_2fa(message)
        else:
            params = request.params
            if params.get("login_success"):
                user = request.env.user
                if user and user.enable_2fa and not user.qr_image_2fa:
                    # If credentials are Okay, but a user doesn't have
                    # QR code, that mean it's first success login with
                    # one-time-password. Now QR Code with it's Secret
                    # Code can be saved into the user.
                    values = {
                        "qr_image_2fa": params.get("qr_code_2fa"),
                        "secret_code_2fa": params.get("secret_code_2fa"),
                    }
                    user.sudo().write(values)

        return response`

Now when I login from a mobile app a user with 2FA activated will not be recognised by the database, only browser (mobile or desktop) access will allow a 2FA user to complete the 2FA process.

**Comment by okuryan** [comment]
Yes, to enable 2FA on Odoo mobile app there should be made modifications to Odoo itself. Older versions of Odoo for which module was written do not have good architecture to create universal module that will add 2FA both on Odoo mobile app and on Desktop.

So this code just removes 2FA when  you try to login from Odoo mobile app
